ALTER TABLE changeset_specs
    ADD COLUMN IF NOT EXISTS diff bytea,
    ADD COLUMN IF NOT EXISTS head_repo_id integer REFERENCES repo(id) ON DELETE CASCADE DEFERRABLE,
    ADD COLUMN IF NOT EXISTS base_rev TEXT,
    ADD COLUMN IF NOT EXISTS base_ref TEXT,
    ADD COLUMN IF NOT EXISTS body TEXT,
    ADD COLUMN IF NOT EXISTS published TEXT,
    ADD COLUMN IF NOT EXISTS commit_message TEXT,
    ADD COLUMN IF NOT EXISTS commit_author_name TEXT,
    ADD COLUMN IF NOT EXISTS commit_author_email TEXT,
    ADD COLUMN IF NOT EXISTS type TEXT,
    ADD COLUMN IF NOT EXISTS migrated BOOLEAN NOT NULL DEFAULT FALSE;
