name: sg-setup
on:
  push:
    paths:
      - 'dev/sg/dependencies/**.go'
      - 'dev/sg/internal/check/**.go'

jobs:
  test:
    strategy:
      matrix:
        # See https://github.com/actions/virtual-environments#available-environments for
        # available environments.
        os: [macos-11, ubuntu-20.04]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test dependencies (${{ matrix.os }})
        if: "! contains(matrix.os, 'ubuntu')"
        run: |
          go test -timeout=30m -v \
            ./dev/sg/dependencies/... -sg-setup=${{ matrix.os }}

      # We need two separate test things to work around a known issue with terminals in
      # GitHub Actions: https://github.com/actions/runner/issues/241#issuecomment-745902718
      - name: Test dependencies (${{ matrix.os }})
        if: contains(matrix.os, 'ubuntu')
        shell: 'script -q -e -c "bash {0}"' # The workaround
        run: |
          go test -timeout=30m -v \
            ./dev/sg/dependencies/... -sg-setup=${{ matrix.os }}
